development:
  adapter: postgresql
  encoding: unicode
  database: tutolw_dev
  pool: 5
  username: tutolw
  password: tutolw6

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: tutolw_production
  pool: 5
  username: tutolw
  password:
